name: Prepare test prerequisites

runs:
  using: "composite"
  steps:
    - name: Checking out repo
      uses: actions/checkout@v4
    - name: Install test dependencies
      shell: bash
      run: |
        set -x
        sudo apt-get install python3-setuptools
        sudo pip3 install --upgrade pip
        sudo pip3 install -U pytest==8.3.4 sh psutil requests
        sudo apt-get -y install open-iscsi
        sudo systemctl enable iscsid
    # Docker sets iptables rules that interfere with LXD and K8s.
    # https://documentation.ubuntu.com/lxd/en/latest/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-lxd-and-docker
    - name: Apply Docker iptables workaround
      shell: bash
      run: sudo iptables -I DOCKER-USER -j ACCEPT
    - name: Fetch snap
      uses: actions/download-artifact@v4
      with:
        name: microk8s.snap
        path: build
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
